{% set version = "0.90" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-metaskat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MetaSKAT_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MetaSKAT/MetaSKAT_{{ version }}.tar.gz
  sha256: e12cb433d872ad87f39f9c65c40f76d5123e0b9493a5c1bf90f1d870c55bd1c6

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-skat
  run:
    - r-base
    - r-skat

test:
  commands:
    - $R -e "library('MetaSKAT')"           # [not win]
    - "\"%R%\" -e \"library('MetaSKAT')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MetaSKAT
  license: GPL-2.0-or-later
  summary: Functions for Meta-analysis Burden test, SKAT and SKAT-O by Lee et al. (2013) <doi:10.1016/j.ajhg.2013.05.010>. These methods use summary-level score statistics to carry out gene-based meta-analysis for rare variants.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
  doc_url: https://CRAN.R-project.org/web/packages/MetaSKAT/MetaSKAT.pdf

extra:
  recipe-maintainers:
    - conda-forge/r
    - matuskosut

# Package: MetaSKAT
# Type: Package
# Title: Meta Analysis for SNP-Set (Sequence) Kernel Association Test
# Version: 0.80
# Date: 2020-03-06
# Author: Seunggeun (Shawn) Lee
# Maintainer: Seunggeun (Shawn) Lee <leeshawn@umich.edu>
# Description: Functions for Meta-analysis Burden test, SKAT and SKAT-O by  Lee et al. (2013) <doi: 10.1016/j.ajhg.2013.05.010>. These methods use summary-level score statistics to carry out gene-based meta-analysis for rare variants.
# License: GPL(>=2)
# SystemRequirements:	Little Endian
# Depends: R (>= 2.13.0)
# Imports: SKAT
